# site settings
title: Open Source
subtitle: .Africa
email: opensourcecommunityafrica@gmail.com
description: A responsive site template designed by HTML5 Up<br /> and released under the Creative Commons.
 # the subpath of your site, e.g. /blog
baseurl: ""
url: "" # the base hostname & protocol for your site
author:
street_address:
city:
state:
zip_code:
country:
phone:

# homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# social settings
facebook_url: https://web.facebook.com/opensourcecommunityafrica/
github_url: https://github.com/oscommunityafrica
googleplus_url:
instagram_url:
linkedin_url:
pinterest_url:
slack_url:
twitter_url: https://twitter.com/oscafrica

# build settings
markdown: kramdown

sass:
  style: compressed
